if &compatible
	" vint: -ProhibitSetNoCompatible
	set nocompatible
	" vint: +ProhibitSetNoCompatible
endif

" Set main configuration directory as parent directory
let $VIM_PATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')

function! s:source_file(path, ...)
	" Source user configuration files with set/global sensitivity
	let use_global = get(a:000, 0, ! has('vim_starting'))
	let abspath = resolve($VIM_PATH . '/' . a:path)

	if ! use_global
		execute 'source' fnameescape(abspath)
		return
	endif

	let tempfile = tempname()
	let content = map(readfile(abspath),
		\ "substitute(v:val, '^\\W*\\zsset\\ze\\W', 'setglobal', '')")
	try
		call writefile(content, tempfile)
		execute printf('source %s', fnameescape(tempfile))
	finally
		if filereadable(tempfile)
			call delete(tempfile)
		endif
	endtry
endfunction

" Initialize startup settings
if has('vim_starting')
	let g:mapleader=","
endif

" Initialize plugin-manager and load main config files
call s:source_file('config/init.vim')
call s:source_file('config/plugins.vim')

" Initialize all my configurations
call s:source_file('config/general.vim')
call s:source_file('config/mappings.vim')
call s:source_file('config/plugin-configurations/coc.vim')
call s:source_file('config/plugin-configurations/csscomplete.vim')
call s:source_file('config/plugin-configurations/deoplete.vim')
call s:source_file('config/plugin-configurations/fruzzy.vim')
call s:source_file('config/plugin-configurations/fzf.vim')
call s:source_file('config/plugin-configurations/LanguageClient-neovim.vim')
call s:source_file('config/plugin-configurations/ranger.vim')
call s:source_file('config/plugin-configurations/ranger.vim')
call s:source_file('config/plugin-configurations/vim-airline.vim')
call s:source_file('config/plugin-configurations/vim-gitgutter.vim')
call s:source_file('config/plugin-configurations/vim-javascript.vim')
call s:source_file('config/plugin-configurations/vim-prettier.vim')
call s:source_file('config/plugin-configurations/vista.vim')
call s:source_file('config/theme.vim')

set secure

" vim: set ts=2 sw=2 tw=80 noet :
